"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Injectable = exports.View = exports.Delete = exports.Post = exports.Patch = exports.Put = exports.Get = exports.Controller = exports.Register = void 0;
var index_1 = require("./views/index");
Object.defineProperty(exports, "View", { enumerable: true, get: function () { return index_1.View; } });
var controller_decorator_1 = require("./decorators/controller.decorator");
Object.defineProperty(exports, "Controller", { enumerable: true, get: function () { return controller_decorator_1.Controller; } });
var http_decorator_1 = require("./decorators/http.decorator");
Object.defineProperty(exports, "Delete", { enumerable: true, get: function () { return http_decorator_1.Delete; } });
Object.defineProperty(exports, "Get", { enumerable: true, get: function () { return http_decorator_1.Get; } });
Object.defineProperty(exports, "Patch", { enumerable: true, get: function () { return http_decorator_1.Patch; } });
Object.defineProperty(exports, "Post", { enumerable: true, get: function () { return http_decorator_1.Post; } });
Object.defineProperty(exports, "Put", { enumerable: true, get: function () { return http_decorator_1.Put; } });
var register_decorator_1 = require("./decorators/register.decorator");
Object.defineProperty(exports, "Register", { enumerable: true, get: function () { return register_decorator_1.Register; } });
var injectable_decorator_1 = require("./decorators/injectable.decorator");
Object.defineProperty(exports, "Injectable", { enumerable: true, get: function () { return injectable_decorator_1.Injectable; } });
